from pathlib import Path
import json, math, os, re, subprocess, tempfile, uuid
from typing import Any
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "cache"
CACHE.mkdir(exist_ok=True)
app = FastAPI(title="Swim AI Pro")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)
class Source(BaseModel):
    url: str

class AnalyzeRequest(BaseModel):
    url: str
    start: float = Field(0, ge=0)
    end: float = Field(..., gt=0)
    pool_length: float = Field(25, gt=0)
    distance: float = Field(200, gt=0)
    stroke: str = "Freestyle"
    walls: list[dict[str, Any]] = []

def valid_youtube(url: str) -> bool:
    return bool(re.match(r"^https?://(www\.)?(youtube\.com|youtu\.be)/", url.strip()))

def yt_info(url: str):
    try:
        p = subprocess.run(["yt-dlp","--dump-single-json","--no-download",url],
                           capture_output=True,text=True,timeout=45,check=True)
        return json.loads(p.stdout)
    except FileNotFoundError:
        raise HTTPException(500,"yt-dlp is not installed. Run: pip install -r requirements.txt")
    except Exception as e:
        raise HTTPException(400,f"Could not inspect YouTube URL: {e}")

def download_clip(url: str, start: float, end: float) -> Path:
    if end <= start: raise HTTPException(400,"End time must be after start time.")
    key = uuid.uuid5(uuid.NAMESPACE_URL, f"{url}|{start:.3f}|{end:.3f}").hex
    out = CACHE / f"{key}.mp4"
    if out.exists(): return out
    # Download a high-quality progressive/merged source, then cut only the requested interval.
    raw = CACHE / f"{key}_raw.%(ext)s"
    try:
        subprocess.run(["yt-dlp","-f","bv*[height<=1080]+ba/b[height<=1080]",
                        "--merge-output-format","mp4","-o",str(raw),url],
                       timeout=900,check=True)
        candidates=list(CACHE.glob(f"{key}_raw.*"))
        if not candidates: raise RuntimeError("Download produced no file")
        src=candidates[0]
        subprocess.run(["ffmpeg","-y","-ss",str(start),"-i",str(src),"-t",str(end-start),
                        "-c","copy",str(out)],timeout=180,check=True,
                       stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
        return out
    except FileNotFoundError:
        raise HTTPException(500,"Install yt-dlp and ffmpeg first.")
    except Exception as e:
        raise HTTPException(400,f"Could not extract clip: {e}")

@app.get("/")
def home(): return FileResponse(ROOT/"frontend"/"index.html")

@app.post("/api/youtube/inspect")
def inspect(s: Source):
    if not valid_youtube(s.url): raise HTTPException(400,"Please enter a YouTube URL.")
    x=yt_info(s.url)
    return {"url":s.url,"title":x.get("title"),"duration":x.get("duration"),"channel":x.get("channel"),
            "thumbnail":x.get("thumbnail"),"note":"Preview is generated by the local backend when a clip is requested."}

@app.post("/api/detect")
def detect(s: AnalyzeRequest):
    clip=download_clip(s.url,s.start,s.end)
    # The production detector hook is intentionally isolated here so a heavier GPU model can be swapped in.
    # See ai_pipeline.py. The endpoint returns a usable response even before model weights are installed.
    from .ai_pipeline import detect_candidates
    result=detect_candidates(str(clip))
    return result

@app.post("/api/analyze")
def analyze(s: AnalyzeRequest):
    clip=download_clip(s.url,s.start,s.end)
    from .ai_pipeline import analyze_clip
    return analyze_clip(str(clip), s.pool_length, s.distance, s.stroke, s.walls)

app.mount("/cache", StaticFiles(directory=CACHE), name="cache")

